parse-usgs-json.py: update USGS URL to https
/var/www/boinc/sensor/log_qcn/get_quakes.out was logging
errors in parsing the USGS JSON:

  Error in parseJSON/var/www/boinc/sensor/usgs-quake.json
  Traceback (most recent call last):
    File "/var/www/boinc/sensor/bin/parse-usgs-json.py", line 99, in parseJSON
      data = simplejson.load(json_data)
    File "/usr/lib64/python2.7/site-packages/simplejson-3.8.2-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 459, in load
      use_decimal=use_decimal, **kw)
    File "/usr/lib64/python2.7/site-packages/simplejson-3.8.2-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 516, in loads
      return _default_decoder.decode(s)
    File "/usr/lib64/python2.7/site-packages/simplejson-3.8.2-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
      obj, end = self.raw_decode(s)
    File "/usr/lib64/python2.7/site-packages/simplejson-3.8.2-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
      return self.scan_once(s, idx=_w(s, idx).end())
  JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Turned out that the unparsable JSON file was actually a 301 response,
redirecting from http to https URL.