Fix isnan() compile error in server scheduler
When compiling the server[1], there are a couple files which can end up
defining both C version of isnan() and C++ version of isnan(), and the
compiler doesn't know which to pick

  error: call of overloaded ‘isnan(double&)’ is ambiguous

Solve the ambiguity by specifically calling the C++ version
via std::isnan()

[1] which is done via boinc checked out to a hacked qcn-specific branch
    that then sneaks over into qcn source, see "QCN server software" in
    toplevel README of this repo